version: "3.9"

services:
  app:
    build: .
    container_name: visit_analyzer_app
    ports:
      - "8803:8080"
    environment:
      - TRANSCRIBE_IMPL=faster-whisper
      - OLLAMA_HOST=http://visit_analyzer_ollama:11434
      - OLLAMA_MODEL=mistral-nemo
      - API_TOKEN=d8v7fhozfdhv8onvfdb
    volumes:
      - .:/code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    networks:
      - visit_net
  visit-ollama:
    image: ollama/ollama:latest
    container_name: visit_analyzer_ollama
    ports:
      - "9902:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    networks:
      - visit_net

volumes:
  ollama_data:

networks:
  visit_net:
    driver: bridge