version: "3.9"

services:
  app:
    build: .
    container_name: visit_analyzer_app
    ports:
      - "8803:8080"
    environment:
      - TRANSCRIBE_IMPL=faster-whisper
      - OLLAMA_HOST=http://ollama:9902
      - OLLAMA_MODEL=mistral_nemo
      - API_TOKEN=d8v7fhozfdhv8onvfdb
    volumes:
      - .:/code
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: visit_analyzer_ollama
    ports:
      - "9902:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
